language: csharp
solution: ./TestApp/TestApp.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore ./TestApp/TestApp.sln

script:
  - xbuild ./TestApp/TestApp.sln
  - nunit-console ./TestApp/UnitTests/bin/Debug/UnitTests.dll